Wrap long tick labels (#17)
* Wrap long x-axis tick text
* Removed unused code and fix typescript warnings.

* Comment out broken test for now
  TypeError: tspan.node(...).getComputedTextLength is not a function